run:
  timeout: 5m
linters-settings:
  errcheck:
    check-type-assertions: true
linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosec
    - goimports
    - ineffassign
    - unused
    - goconst
    - misspell
    - unparam
